# Generated by Django 2.2.5 on 2019-12-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('convocatorias', '0001_initial'), ('convocatorias', '0002_auto_20190722_0054'), ('convocatorias', '0003_auto_20190722_0130'), ('convocatorias', '0004_auto_20190722_0155'), ('convocatorias', '0005_auto_20190722_2315'), ('convocatorias', '0006_auto_20190722_2352'), ('convocatorias', '0007_auto_20190723_0005'), ('convocatorias', '0008_auto_20190723_1729'), ('convocatorias', '0009_auto_20190723_1731'), ('convocatorias', '0010_auto_20190723_1749')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('cuce', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('entidad', models.CharField(max_length=251)),
                ('modalidad', models.CharField(max_length=5)),
                ('objetoContratación', models.TextField(verbose_name='Objeto de Contratación')),
                ('estado', models.CharField(max_length=48)),
                ('montoContrato', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto Contrato en Bs.')),
                ('fechaPresentación', models.DateField(null=True, verbose_name='Fecha Presentación')),
                ('fechaPublicación', models.DateField(null=True, verbose_name='Fecha Publicación')),
                ('archivos', models.TextField()),
                ('formularios', models.TextField()),
                ('personaContacto', models.CharField(max_length=250, verbose_name='Persona de Contacto')),
                ('garantía', models.CharField(max_length=255, null=True)),
                ('costoPliego', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Costo Pliego')),
                ('arpc', models.CharField(max_length=10)),
                ('reuniónAclaración', models.DateTimeField(null=True, verbose_name='Fecha de la Reunión de Aclaración')),
                ('fechaAdjudicaciónDesierta', models.DateField(null=True)),
                ('departamento', models.CharField(max_length=15)),
                ('normativa', models.CharField(max_length=150)),
            ],
        ),
    ]
