# Generated by Django 2.2.3 on 2019-07-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='costoPliego',
            field=models.IntegerField(null=True),
        ),
    ]
