# Generated by Django 2.2.3 on 2019-07-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_auto_20190722_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='fechaPresentación',
            field=models.DateField(null=True),
        ),
    ]
