# Generated by Django 2.2.3 on 2019-07-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_auto_20190721_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='personaContacto',
            field=models.CharField(max_length=250),
        ),
    ]
