# Generated by Django 2.2.3 on 2019-07-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_auto_20190722_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='montoContrato',
            field=models.IntegerField(default=0),
        ),
    ]
