# Generated by Django 2.2.3 on 2019-07-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0006_auto_20190722_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='estado',
            field=models.CharField(max_length=48),
        ),
    ]
