# Generated by Django 2.2.3 on 2019-07-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0007_auto_20190723_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='costoPliego',
            field=models.IntegerField(null=True, verbose_name='Costo Pliego'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='fechaPresentación',
            field=models.DateField(null=True, verbose_name='Fecha Presentación'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='fechaPublicación',
            field=models.DateField(null=True, verbose_name='Fecha Publicación'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='montoContrato',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto Contrato'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='objetoContratación',
            field=models.TextField(verbose_name='Objeto de Contratación'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='personaContacto',
            field=models.CharField(max_length=250, verbose_name='Persona de Contacto'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='reuniónAclaración',
            field=models.DateTimeField(null=True, verbose_name='Fecha de la Reunión de Aclaración'),
        ),
    ]
