# Generated by Django 2.2.3 on 2019-07-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0008_auto_20190723_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='montoContrato',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto Contrato en Bs.'),
        ),
    ]
