# Generated by Django 2.2.3 on 2019-07-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0009_auto_20190723_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='costoPliego',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Costo Pliego'),
        ),
    ]
